apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ctse-item-mangement
  name: ctse-item-mangement
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: ctse-item-mangement
status:
  loadBalancer: {}
